name: Update Fuel Prices

on:
  schedule:
    - cron: "17 12 * * 4"
    - cron: "17 12 * * 5"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      
      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run historical price ingestion
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: python -m ingestion.ingestion.fetch_historical_prices

      - name: Create dbt profile
        env:
          DBT_PROFILES: ${{ secrets.DBT_PROFILES }}
        run: |
          mkdir -p ~/.dbt
          echo "$DBT_PROFILES" > ~/.dbt/profiles.yml

      - name: Install dbt
        run: pip install dbt-postgres

      - name: Run dbt
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          cd dbt/fuel_prices
          dbt build





